# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master
- features/*

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  resharperSolution: 'BatteryStatus/BatteryStatus.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  version: '0.1.0.$(Build.BuildId)'

stages:
- stage: rl0_stage
  displayName: 'Release stage 0'
  jobs:
  - job: default
    displayName: 'Default pipeline job'
    timeoutInMinutes: 15
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: ResharperCli@2
      timeoutInMinutes: 5
      inputs:
        solutionOrProjectPath: '$(resharperSolution)'
        buildId: '$(version)'

    - task: DeleteFiles@1
      displayName: 'Delete ReSharper from staging directory'
      inputs:
        sourceFolder: '$(Build.ArtifactStagingDirectory)'
        contents: |
          **/*

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        msbuildArgs: '/p:TreatWarningsAsErrors="true"'

    - task: VSTest@2
      inputs:
        # xUnit assembly filters from https://xunit.net/docs/getting-test-results-in-azure-devops
        testAssemblyVer2: |
          **/bin/$(buildConfiguration)/**/*test.dll
          !**/obj/**
          !**/xunit.runner.visualstudio.testadapter.dll
          !**/xunit.runner.visualstudio.dotnetcore.testadapter.dll
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
        codeCoverageEnabled: True

    - task: CopyFiles@2
      displayName: 'Copy build to staging directory'
      inputs:
        Contents: '**/build/$(buildConfiguration)/**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'BatteryStatus_$(version)'
        publishLocation: 'Container'
